services:
  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "6789:6789"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/desafio_imposto
      SPRING_DATASOURCE_USERNAME: imposto
      SPRING_DATASOURCE_PASSWORD: 12345
    depends_on:
      - postgres-db
    restart: on-failure

  postgres-db:
    image: postgres:17
    container_name: postgres-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: desafio_imposto
      POSTGRES_USER: imposto
      POSTGRES_PASSWORD: 12345
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: on-failure

volumes:
  postgres-data: